/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CatalogEntry {
  'id' : string,
  'order' : bigint,
  'name' : string,
  'imageUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBranch' : ActorMethod<[string, string], undefined>,
  'addHero' : ActorMethod<[string, string], undefined>,
  'addItem' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBranch' : ActorMethod<[string], undefined>,
  'deleteHero' : ActorMethod<[string], undefined>,
  'deleteItem' : ActorMethod<[string], undefined>,
  'getBranches' : ActorMethod<[], Array<CatalogEntry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHeroes' : ActorMethod<[], Array<CatalogEntry>>,
  'getItems' : ActorMethod<[], Array<CatalogEntry>>,
  'initializeCatalogs' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateBranch' : ActorMethod<[string, string, string], undefined>,
  'updateHero' : ActorMethod<[string, string, string], undefined>,
  'updateItem' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];