/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CatalogEntry = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBranch' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addHero' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBranch' : IDL.Func([IDL.Text], [], []),
  'deleteHero' : IDL.Func([IDL.Text], [], []),
  'deleteItem' : IDL.Func([IDL.Text], [], []),
  'getBranches' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHeroes' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
  'getItems' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
  'initializeCatalogs' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateBranch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateHero' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CatalogEntry = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBranch' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addHero' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addItem' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBranch' : IDL.Func([IDL.Text], [], []),
    'deleteHero' : IDL.Func([IDL.Text], [], []),
    'deleteItem' : IDL.Func([IDL.Text], [], []),
    'getBranches' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHeroes' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
    'getItems' : IDL.Func([], [IDL.Vec(CatalogEntry)], ['query']),
    'initializeCatalogs' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateBranch' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateHero' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };